config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"

  root 'home#index'
  
  get '/signup' => 'accounts#new'
  post '/signup' => 'accounts#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  namespace :accounts, as: 'accounts', constraints: { id: User::USERNAME_FORMAT } do
    get '/passwords/forgot' => 'passwords#new'
    post '/passwords/forgot' => 'passwords#create'

    resources :passwords, only: [:edit, :update]
    resources :activations, only: [:new, :edit] 
  end
  
  resource :account, only: [:edit] do 
    patch '/edit', action: :update
    put '/edit', action: :update
  end

  constraints( id: /\d+/ ) do
    resources :articles
    resources :categories, only: [:create, :update, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy] do
      member do
        get :reply
      end
    end
  end

  # 上传图片
  match '/pictures' => 'pictures#create', via: [:post, :patch, :put]
  # 暂存文章/简历
  match '/holds' => 'holds#update', via: [:post, :patch, :put]

  # 控制台
  namespace :admin, as: 'admin' do
    root 'home#index', as: 'index'
    resources :users, except: :show
    resources :articles, except: :show
    resources :categories, except: :show
    resources :tags, except: :show
    resources :comments, except: :show
    resources :pictures, only: [:index, :destroy, :create]
  end

  # 社区
  scope :community, as: 'community' do
    root 'community#index', as: 'index'
    get '/hottest' => 'community#hottest'
    get '/latest' => 'community#latest'
    get '/search' => 'search#index'
    get '/tags/:id' => 'community#tag', as: 'tag'
    get '/articles' => 'community#articles'
    get '/users' => 'community#users'
  end

  # users相关路由最后
  resources :users, only: [:show] , path: '' , constraints: { id: User::USERNAME_FORMAT } do
    member do
      get :categories
      get :aboutme
      get :drafts
      get :archive
      get :blog
      get '/categories/:category_id', as: 'category', to: 'users#category'
      get '/tags/:tag_id', as: 'tag', to: 'users#tag'
      get '/search', to: 'search#show'
      get '/resume', to: 'resumes#show'
      match '/resume', to: 'resumes#update', via: [:patch, :put]
      get '/resume/edit', to: 'resumes#edit'
      post :follow
      post :unfollow
    end
  end

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::ApplicationController

  def index
    @summary = {
      user:      { total: User.all.size,     normal: User.normal.size, 
                   admin: User.admin.size,   disabled: User.disabled.size  },
      article:   { total: Article.all.size,  posted: Article.posted.size, 
                   unposted: Article.unposted.size },
      category:  { total: Category.all.size, used: Category.used.size,
                   unused: Category.unused.size },
      tag:       { total: Tag.all.size,      used: Tag.used.size,
                   unused: Tag.unused.size },
      comment:   { total: Comment.all.size,  posted: Comment.posted.size,
                   deleting: Comment.deleting.size },
      picture:   { total: Picture.all.size,  posted: Picture.posted.size,
                   unposted: Picture.unposted.size }
    }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
  def user_state(user)
    return nil if user.blank?
    case user.state
      when 0
        I18n.t "c-summary.user.disabled"
      when 1
        I18n.t "c-summary.user.normal"
      when 2
        I18n.t "c-summary.user.admin"
    end
  end

  def user_state_selected_tags(selected_value)
    value = 
      if selected_value.blank?
        1
      else
        selected_value
      end
    options = ""
    states = [I18n.t("c-summary.user.disabled"), I18n.t("c-summary.user.normal"), I18n.t("c-summary.user.admin")]
    states.each_with_index do |name, index|
      options += 
        if index != value
          content_tag :option, name, value: index 
        else
          content_tag :option, name, value: index, selected: 'selected'
        end
    end
    raw options
  end

  def boolean_selected_tags(selected_value)
    value = selected_value
    value = false if selected_value.blank?
    options = ""
    state = [true, false]
    state.each do |item|
      options +=
        if item != value
          content_tag :option, item, value: item 
        else
          content_tag :option, item, value: item, selected: 'selected'
        end
    end
    raw options
  end

end

app/views/home/index.html.erb
<div class="login">

  <div class="login-group">
  <% unless signed_in? %>
    <%= link_to t('signup'), signup_path %>&nbsp;|&nbsp;
    <%= link_to t('signin'), signin_path %>
  <% else %>
    <%= link_to t('signout'), signout_path, method: 'DELETE' %>&nbsp;|&nbsp;
    <%= link_to t('signed_in'), user_path(current_user.username)%>
  <% end %>
  </div>
  
  <%= content_tag :div, link_to_locale(request.path), class: "switch-lang" %>
  <div class="clearfix"></div>
  <div class="container">
    <div class="col-sm-4 col-md-4 col-center-block login-box">
      <div class="logo col-sm-9 col-md-10 col-center-block">
        <%= link_to image_tag("logo.png", alt:"Milog", class: "img-responsive center-block"), "/" %>
      </div>
      
      <h6></h6>
      <div class="clearfix"></div>

      <%= content_tag :div, t("community.slogan"), id: "slogan" %>
      <%= content_tag :h5, t("community.sub_slogan"), id: 'sub-slogan' %>

      <ul class="tab" id="social-menu">
          <%= content_tag :li, link_to(t("community.our_social"), community_index_path) %>
          <% unless signed_in?  %>
            <%= content_tag :li, link_to(t("community.join_us"), signup_path) %>
          <% else %>
            <%= content_tag :li, link_to(t("community.my_space"), user_path(current_user.username)) %>
          <% end %>
      </ul>

    </div>
  </div>
</div>